language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: NaQcGeURH0OOGF8pM9g0PCY4zlrlZaJN7tiOhUAOiqNIH+qFZxvTyfs6gZlgflmzPFyA9ryIJA+5flMzKD0K32jbuBBXwF3QAMuTZy+l7QlNq3QU0kkRxU++sPavs+UMgkxjIm7tyYDnQJylNMGFE8Dc5oiyHL4TvKweUFUg7yCwsaT9mV2y5/lKAZ/xWjpD+KpYomIMAnbwvP6n1yWN1GW+loxgYn/Ria0f56R86sMe2+7DKav5quf49Sic0HtJpGxgSiW9QhiN63+Q1i2aRCU5ySJXs+Xv5FOm8OuARxG0SnjNv01SMb7z7MwmyrM5XjlfI6Ht69kLFvohI2eRI7aThrh4o/rpPfXVJ2jl4v4gu2w8tPGnlj4Z3NQUUJjB4k7J+2qKRByN9QjGSgyLc1SuRGiy3DfAUnK+V2BpLFoS4B25TJO3qEHjGmeHH1U/K87GlPlcgiJDMJbB0yh++pgBzm9itsWyzirpsfRS6zN1WUc661Qx7xBzNEo0THF15/zio7ttKc4L8wLmUxQ2SIM0Z8fZHPxQFsOqNfS/W3xsAbVbQnPK16DKAagxA6qLSq4QQcRwxHorFRYmL6Xory5IGJIJAUOIoNnl8QlBNmCxCrMyS9SX2DDnf9fc5GCrCfsDzqWxZqt4jxxaYy6nOFAxSnO5n/dIpG6vXY1Whdo=
