language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: maj5Do7Bmi2JG8yWHFC0waqM/2mUPr7koRbNDArd5DHmUTV7YdJmbhE/JFBTyMsVkFUeGlbqtSBwoZMn62e8MLgmq1u/qGCV0RGPP5XxQvyNNo5va3WaKstPNfC/ACUhT08aIEJNAlbZ776xva3f1WI75xFxKF7XmYAIrDG1SqLGgSkWB3m2YvIq+y8tdqpqlfpnE9vGlqoaYLiD0z6BjD5UfS2ywA5FeCggyb2pFaAXq5PDl75CTL0yQEqvSSs97rbaHJVbIM7h5EoOzOaghBaRBhs+ln77qcmWmOq/JxErttF22agrNYTw3LvFtWWQcaOq8TWFziXc16nTAq94bihoz5mQai2x4Yl4tzXXjYAcqh7U0x7BbY0efS8QoAxvlBthQpt/a23VCF2gJLez4bQMaBfeBbjucjE7MfY7dfKWnTCY0TQVfxsUhmzd9wz24AYMiHz9tmHsCMnQHoSevMUOPmOG4Z0JHNfep67WP22/H77bW7QG4rHwaSr1iGk0HMQIWKkEXgyACJ65S7PAxI62y8/uHpbhEtfpfdiXRvb9sq8mpWdN9ysn+CyPaMKoNltMKK24t6o5fxKe0Mlu2EVaFwM5f8ZJOcWAUXL6AAv6msYJqEW05ld2/Y5KAcfFEjKe42yrOCZL+kgY3bbHKXfh9OQ0HzmrATUZLBn6Mkk=
