language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: RDmOvh5FIs7fh59p8ifF7SZNMvma7i6dH07flJYaFHmH3QVpDidMzjK4SoGPTjx5DwScO3yQQqFEcJkN4G2cfX7uV9zVE9MRCIkGZbhSKUy2R0sMCSRiEEZ6Lg4oK3wttHOo7u2sGSkkkosEF0WQJGSUia/XRAzdfvJIVprEtZ038NfgrRyLVaO61CdDKOGJVmiETJYC0SFqoinOFH7t4sUBh5s4dc6/iRH0lzdBRXF6hsCpr48LjjhIUg0GgOOpJbhbxHseJA3y9eL+xAEndlYvQLX3L8717fdDHPhCkIj5aYnfmNqrAkLejaWCnJq9gWl6TUH27RtH2ssRDqRRAElVv+ewRudEW6ANGnytsyeJMnKrnAR3O8XC7gFrLTpo+Vf5pBuUZ91im/cQHBJ3LFsrN7mzzMIWbU2Uja7NqvLMr2ecziE4u9lFXjT0zhEZRYAdXE0OmDqLtAOHppxuYV079sriCLqdCdnVendQGaOJLVj1q1dscWZrFc64amwdYooB1nTuJPLxTIkyeZMLCs/Ibb/Jjp2itRkbhPnZu2khyYBOOcoOGesRR5hSx+a8GBNJgx776nEFzD/AfvY7ZXNHhZf2YR5xWDUlM4h8wGYg5vRGB+K3bMCOd/kjQ+fxauT8NjXscrf3cqSHk/smgyRLv1uRWuTndoeV4XPfAVg=
